version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.locarpay.rule=Host(`app.locarpay.com.br`)"
        - "traefik.http.routers.locarpay.entrypoints=websecure"
        - "traefik.http.routers.locarpay.tls.certresolver=myresolver"
        - "traefik.http.services.locarpay.loadbalancer.server.port=3000"
    networks:
      - LocarPayNet

networks:
  LocarPayNet:
    external: true
