# Versão do Docker Compose
version: '3.8'

# Definição dos serviços (contêineres)
services:
  # Nome do nosso serviço principal
  app:
    # A imagem que você construiu e enviou para o Docker Hub
    image: locarpay/locarpay-digital-trust-10:1.1
    
    # Política para reiniciar o contêiner automaticamente se ele parar
    restart: always
    
    # Conecta este serviço à rede externa do Traefik, que você nomeou como LocarPayNet
    networks:
      - LocarPayNet
      
    # Injeta as variáveis de ambiente no contêiner.
    # O código da sua aplicação (Vite) lerá estas variáveis.
    environment:
      # !! IMPORTANTE: Substitua os valores abaixo pelos seus dados reais do Supabase !!
      - VITE_SUPABASE_URL=https://jefofujjcqwblavoybfx.supabase.co
      - VITE_SUPABASE_ANON_KEY=sua-chave-anon-publica-aqui-do-supabase
      
    # Etiquetas (labels) que o Traefik usa para configurar o roteamento automaticamente
    labels:
      # Habilita o Traefik para este serviço
      - "traefik.enable=true"
      
      # Define a regra para o roteador: quando a URL for app.locarpay.com.br
      - "traefik.http.routers.locarpay-router.rule=Host(`app.locarpay.com.br`)"
      
      # Define o ponto de entrada que o roteador deve usar (websecure é para HTTPS/443)
      - "traefik.http.routers.locarpay-router.entrypoints=websecure"
      
      # Habilita o resolvedor de certificados SSL (Let's Encrypt) para este roteador
      - "traefik.http.routers.locarpay-router.tls.certresolver=myresolver" # Verifique se 'myresolver' é o nome correto no seu Traefik
      
      # Informa ao Traefik para qual porta interna do contêiner ele deve enviar o tráfego
      - "traefik.http.services.locarpay-service.loadbalancer.server.port=3000"

# Definição das redes usadas nesta stack
networks:
  # Declara que 'LocarPayNet' é uma rede que já existe e foi criada externamente
  LocarPayNet:
    external: true
