version: '3.8'

services:
  app:
    # A imagem do seu front-end que está no Docker Hub
    image: seu-usuario-dockerhub/locarpay-digital-trust-10:latest # <-- SUBSTITUA COM SEU USUÁRIO
    restart: always
    networks:
      - traefik-public
      
    # Injetando as chaves do Supabase de forma segura
    # Sua aplicação TypeScript deve usar process.env.SUPABASE_URL e process.env.SUPABASE_ANON_KEY
    environment:
      - SUPABASE_URL=https://<id-do-projeto>.supabase.co   # <-- COLE SUA URL AQUI
      - SUPABASE_ANON_KEY=sua-chave-anon-publica-aqui     # <-- COLE SUA CHAVE ANON AQUI
      
    labels:
      # --- Labels do Traefik para expor o front-end ---
      - "traefik.enable=true"
      - "traefik.http.routers.locarpay-router.rule=Host(`app.locarpay.com.br`)"
      - "traefik.http.routers.locarpay-router.entrypoints=websecure"
      - "traefik.http.routers.locarpay-router.tls.certresolver=myresolver"
      - "traefik.http.services.locarpay-service.loadbalancer.server.port=3000" # Porta interna da aplicação

networks:
  traefik-public:
    external: true
